FROM quay.io/condaforge/mambaforge

RUN mamba install -c conda-forge \
    python=3.11 \
    voila \
    ipywidgets \
    leafmap \
    rasterio \
    scikit-learn \
    pandas \
    matplotlib \
    numpy \
    xyzservices \
    -y
